---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vyos-demo
data:
  config.boot: |
    system {
        host-name vyos-k8s-demo
        login {
            user vyos {
                authentication {
                    encrypted-password $6$QxPS.uk6mfo$9QBSo8u1FkH16gMyAVhus6fU3LOzvLR9Z9.82m3tiHFAxTtIkhaZSWssSgzt4v4dGAL8rhVQxTg0oAG9/q11h/
                    plaintext-password ""
                }
            }
        }
        syslog {
            global {
                facility all {
                    level info
                }
                facility protocols {
                    level debug
                }
            }
        }
        ntp {
            allow-client {
                address 127.0.0.0/8
                address 169.254.0.0/16
                address 10.0.0.0/8
                address 172.16.0.0/12
                address 192.168.0.0/16
                address ::1/128
                address fe80::/10
                address fc00::/7
            }
            server "time1.vyos.net"
            server "time2.vyos.net"
            server "time3.vyos.net"
        }
        console {
            device ttyS0 {
                speed 115200
            }
        }
        config-management {
            commit-revisions 100
        }
    }
    
    interfaces {
        loopback lo {
        }
    }
  config.command: |
    set interfaces bridge br0 address '172.30.0.1/24'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vyos
  labels:
    app: vyos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vyos
  template:
    metadata:
      labels:
        app: vyos
      annotations:
        k8s.v1.cni.cncf.io/networks: default/vxlan2
    spec:
      containers:
      - name: vyos
        image: tjjh89017/vyos-k8s:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
          - name: config
            mountPath: "/config"
      volumes:
        - name: config
          configMap:
            name: vyos-demo
